export const REQUEST_CONFIRMED_CASES_LIST = "REQUEST_CONFIRMED_CASES_LIST";
export const CONFIRMED_CASES_LIST_RECEIVED = "CONFIRMED_CASES_LIST_RECEIVED";
export const REQUEST_GENERAL_STATS = "REQUEST_GENERAL_STATS";
export const GENERAL_STATS_RECEIVED = "GENERAL_STATS_RECEIVED";
